# Generated by Django 2.2.4 on 2019-08-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('group_img', models.ImageField(blank=True, null=True, upload_to='')),
                ('group_info', models.TextField()),
                ('master_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'PENDING'), ('a', 'ACCEPTED'), ('r', 'REFUSE')], max_length=1)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.Group')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='group',
            field=models.ManyToManyField(related_name='people', through='users.GroupMember', to='users.Group'),
        ),
    ]
