# Generated by Django 2.2.4 on 2019-08-19 10:27

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='기본프로필.png', null=True, upload_to='profile_pics'),
        ),
    ]
