# Generated by Django 2.2.4 on 2019-08-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190814_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='interest',
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(blank=True, choices=[('음식', '음식'), ('스포츠', '스포츠'), ('코딩', '코딩'), ('여행', '여행'), ('컴퓨터', '컴퓨터'), ('게임', '게임'), ('영화', '영화'), ('언어', '언어'), ('예술', '예술'), ('음악', '음악'), ('경훈', '경훈')], max_length=20, null=True, related_name='interests', to='users.Profile')),
            ],
        ),
    ]
