# Generated by Django 2.2.4 on 2019-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190814_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, max_length=20, null=True, related_name='users', to='users.Interest'),
        ),
        migrations.RemoveField(
            model_name='interest',
            name='name',
        ),
        migrations.AddField(
            model_name='interest',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
