# Generated by Django 2.2.4 on 2019-08-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_group_master_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='기본프로필.png', upload_to='profile_pics'),
        ),
    ]
