# Generated by Django 2.2.4 on 2019-08-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_intro',
            field=models.TextField(),
        ),
    ]
