# Generated by Django 2.2.4 on 2019-08-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190809_1642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_intro',
            new_name='group_info',
        ),
    ]
