# Generated by Django 2.2.4 on 2019-08-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190809_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_creater',
            new_name='group_creator',
        ),
    ]
