# Generated by Django 2.2.4 on 2019-08-12 06:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('added', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, related_name='contacts', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='membership',
            name='from_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Membership.from_group+', to='blog.Group'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Membership.to_user+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JoinInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('status', models.CharField(choices=[('1', 'Created'), ('2', 'Sent'), ('3', 'Failed'), ('4', 'Expired'), ('5', 'Accepted'), ('6', 'Declined'), ('7', 'Joined Independently'), ('8', 'Deleted')], max_length=1)),
                ('confirmation_key', models.CharField(max_length=40)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Contact')),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups2', to='blog.Group')),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipInvitationHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('status', models.CharField(choices=[('1', 'Created'), ('2', 'Sent'), ('3', 'Failed'), ('4', 'Expired'), ('5', 'Accepted'), ('6', 'Declined'), ('7', 'Joined Independently'), ('8', 'Deleted')], max_length=1)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_from_history', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_to_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FriendshipInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent', models.DateField(default=django.utils.datetime_safe.datetime.now)),
                ('status', models.CharField(choices=[('1', 'Created'), ('2', 'Sent'), ('3', 'Failed'), ('4', 'Expired'), ('5', 'Accepted'), ('6', 'Declined'), ('7', 'Joined Independently'), ('8', 'Deleted')], max_length=1)),
                ('from_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='blog.Group')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
