# Generated by Django 2.2.4 on 2019-08-12 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20190812_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendshipinvitation',
            name='from_group',
        ),
        migrations.RemoveField(
            model_name='friendshipinvitation',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='friendshipinvitationhistory',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='friendshipinvitationhistory',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='group',
            name='group_creator',
        ),
        migrations.RemoveField(
            model_name='joininvitation',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='joininvitation',
            name='from_group',
        ),
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membership',
            name='from_group',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FriendshipInvitation',
        ),
        migrations.DeleteModel(
            name='FriendshipInvitationHistory',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='JoinInvitation',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
